### ISSUE TITLE
Publish pys2index on PyPI

### ISSUE THREAD

**Issue by zklaus** [benbovy/pys2index#6]
I just started using Pys2index to order earth observational stations in a Netcdf file for geographic proximity. It works like a charm, thank you!

Currently, I install it simply via Conda-forge, which also works great. Still, I would like to integrate it into our packages dependency management via the usual Python mechanisms, i.e. `pyproject.toml`/`setup.py` requirements.

Therefore, I would like to suggest to publish Pys2index to PyPI. I realize that it might be challenging to do a full-blown binary distribution with wheels, but a pure source distribution would go a long way and is generally also the preferred source for Conda-forge packages.

Is this something you would be open to?

**Comment by benbovy** [comment]
@zklaus I'm glad it is working well for you. And sorry for long wait.

Yes I'm be open to publish a source package to PyPI. I'll see if I can setup that and then publish a new release along with updating the default standard to C++17 (cf. https://github.com/conda-forge/pys2index-feedstock/pull/14).

**Comment by zklaus** [comment]
Thanks, @benbovy, sounds great! Sorry that it was now me who kept you waiting. Holidays...

I also wanted to note that upstream, i.e. S2 seems to want to move to pybind11 bindings, in case you are interested.

Anyway, let me help if I can help here with Pypi support.

**Comment by benbovy** [comment]
> I also wanted to note that upstream, i.e. S2 seems to want to move to pybind11 bindings, in case you are interested.

I noticed it, but it is unclear to me when they will make the move. Also, a while ago we started working on Python / NumPy vectorized bindings with a shapely-like API: https://github.com/benbovy/spherely

> Anyway, let me help if I can help here with Pypi support.

Do you want to give it a shot? I don't have much time for that ATM unfortunately. One option could be using https://vcpkg.io for getting the dependencies, like for [pyogrio](https://github.com/geopandas/pyogrio/blob/main/.github/workflows/release.yml) does. There are packages for S2Geometry.

**Comment by zklaus** [comment]
> > Anyway, let me help if I can help here with Pypi support.
> 
> Do you want to give it a shot? I don't have much time for that ATM unfortunately. One option could be using https://vcpkg.io for getting the dependencies, like for [pyogrio](https://github.com/geopandas/pyogrio/blob/main/.github/workflows/release.yml) does. There are packages for S2Geometry.

Ah, I had something much simpler in mind, that is, just to publish the source archive, no wheels or other binaries on Pypi. Would that be ok?

**Comment by benbovy** [comment]
Yes that's ok for me!

**Comment by benbovy** [comment]
Recently I started using the `cibuildwheel` github action in another project that I maintain https://github.com/fastscape-lem/fastscapelib and I found the experience very smooth.

The main effort in publishing binary wheels on pypi would be to bundle s2geometry (and xtensor-python), but even that I don't think it would be a big deal.

**Comment by benbovy** [comment]
> The main effort in publishing binary wheels on pypi would be to bundle s2geometry (and xtensor-python), but even that I don't think it would be a big deal.

Hmm I forgot that s2geometry now explicitly depends on abseil. I might skip building binary wheels for now.

**Comment by benbovy** [comment]
Version 0.1.5 is released and published on PyPI (source only). @zklaus normally you should have received an invite to co-maintain the package there.
